# Removed version as it's obsolete in newer Docker Compose

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: errlog_backend
    ports:
      - "8080:8000"
    volumes:
      - ./backend:/app
      - ./sample_logs:/app/sample_logs
    environment:
      - ENVIRONMENT=development
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: errlog_frontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    command: npm run dev

  redis:
    image: redis:7-alpine
    container_name: errlog_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: